
name: fitness_uncensored
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Presentations
  cupertino_icons: ^1.0.4
  flutter_svg: ^0.22.0
  easy_localization: ^3.0.0
  adaptive_theme: ^2.3.0
  flutter_screenutil: ^5.0.2
  dotted_border: ^2.0.0+1
  shimmer: ^2.0.0
  lottie: ^1.2.1
  pull_to_refresh: ^2.0.0
  app_review: ^2.1.1+1
  pinput: ^1.2.2
  carousel_slider: ^4.0.0
  flutter_html: ^2.1.5
  percent_indicator: ^3.4.0
  syncfusion_flutter_charts: ^19.4.41
  chewie: ^1.3.1
  permission_handler: ^9.2.0

  # Infrastructure
  dartz: ^0.10.1
  flutter_bloc: ^7.3.3
  freezed: ^1.1.0
  built_value: ^8.1.3
  connectivity: ^3.0.6
  dio: ^4.0.4
  get_it: ^7.2.0
  google_sign_in: ^5.2.3
  sign_in_with_apple: ^3.3.0
  path_provider: ^2.0.8
  image_picker: ^0.8.4+5
  url_launcher: ^6.0.17

  # Local database
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  # Firebase
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  firebase_dynamic_links: ^4.0.3

  # security
  encrypt: ^5.0.1

  # Utils
  enum_to_string: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3
  hive_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
     - assets/svg/
     - assets/fonts/
     - assets/animations/
     - assets/translations/
     - assets/images/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/Sans-regular.ttf
          weight: 400
        - asset: assets/fonts/Sans-bold.ttf
          weight: 700
